New Comit for feature/API-23-Document.Structure.Resource.Fields
jmlue42/spectral-jsonapi-ruleset pull request #58
Opened 2023-12-23 08:43 UTC by saujany

2023-12-23 08:50 UTC, saujany commented
Since older branch was there for  feature/API-23  may be reason it was not able to create PR as it was trying to map with old existing feature branch, I have changed branch name to "feature/API-23-Document.Structure.Resource.Fields" from 
feature/API-23-Document-Structure-Resource-Fields

2023-12-26 16:39 UTC, ezenity reviewed
Each of your `invalidApiDocuments...` had linting errors. They can be resolved by running the following command:

`eslint **/*.js /test`

2023-12-26 16:39 UTC, ezenity commented on rules/jsonapi-document-structure-resource-fields.js
> +
Please remove this empty line (line 11) for cleaner code formatting.

2023-12-26 16:39 UTC, ezenity commented on rules/jsonapi-document-structure-resource-fields.js
> +
Please remove this empty line (line 24) for cleaner code formatting.

2023-12-26 16:39 UTC, ezenity commented on rules/jsonapi-document-structure-resource-fields.js
> +  rules: {
The rules you have created are individually targeting each area where we want to enforce the specifications for JSON:API v1.0 DocumentStructure.ResourceObjects.Fields.

However, you are currently only targeting the specifications where a `Resource Object` is an array. Per JSON:API v1.0 DocumentStructure.TopLevel Specifications for `Resource Objects`, the primary data **MUST** be either:

- a single `resource object`, a single `resource identified object`, or null, for a requests that target single resources
- An array of `resource objects`, an array of `resource identifier objects`, or an empty array, for requests that target resource collections. 

Your current ruleset does not target all of these possibilities where we must validate against. You must either adjust your current `JSONPath Expressions` to consider these possibilities or create additional rules to target these specifications per JSON:API v1.0.

2023-12-26 16:39 UTC, ezenity commented on test/jsonapi-document-structure-resource-fields.test.js
> +import validApiDocument from './docs/validApiDocument.js';
Please remove line 21 as it is unnecessary and does not contribute to the functionality. 

You are currently using the global method for the `validApiDocument`

2023-12-26 16:39 UTC, ezenity commented on test/jsonapi-document-structure-resource-fields.test.js
> +/* eslint-env mocha */
This file has `142` linting errors.

Please run the following comment to resolve these linting errors:

- `eslint **/*.js /test --fix`

If you add more test cases to this file please make sure to run the command above to ensure you are following the linting rules expectations.

2023-12-26 16:43 UTC, ezenity requested changes

2023-12-26 16:43 UTC, ezenity commented on test/docs/errors/resourceObjectFields/invalidApiDocumentAttributesIdNotRequired.js
> +const invalidApiDocumentAttributesIdNotRequired ={
This line is generating linting errors. It can be resolved by running the following command:

`eslint **/*.js /test`

2023-12-26 16:43 UTC, ezenity commented on test/docs/errors/resourceObjectFields/invalidApiDocumentAttributesTypeNotRequired.js
> +const invalidApiDocumentAttributesTypeNotRequired ={
This line is generating linting errors. It can be resolved by running the following command:

`eslint **/*.js /test`

2023-12-26 16:43 UTC, ezenity commented on test/docs/errors/resourceObjectFields/invalidApiDocumentRelationshipsIdNotRequired.js
> +const invalidApiDocumentRelationshipsIdNotRequired ={
This line is generating linting errors. It can be resolved by running the following command:

`eslint **/*.js /test`

2023-12-26 16:43 UTC, ezenity commented on test/docs/errors/resourceObjectFields/invalidApiDocumentRelationshipsTypeNotRequired.js
> +const invalidApiDocumentRelationshipsTypeNotRequired ={
This line is generating linting errors. It can be resolved by running the following command:

`eslint **/*.js /test`

2023-12-27 15:35 UTC, closed without merging