Updated tests to support Windows.
jmlue42/spectral-jsonapi-ruleset pull request #77
Opened 2024-02-23 09:18 UTC by DawMatt

As per issue https://github.com/jmlue42/spectral-jsonapi-ruleset/issues/75 , the existing test failed to run on Windows. The revised npm test command works on both Windows and Mac, as the removed text (node_modules/.bin) is automatically inserted at the beginning of the PATH before executing.

2024-02-23 13:25 UTC, tnederveld commented
Couldn't you use 'npx spectral lint examples/valid/* -r ./.spectral.yml' which would also make sure that the dependent packages are installed before running the linter. Using either 'node_modules/.bin' or 'spectral' is making an assumption that the NPM package is already installed by the user. I'd suggest using 'npx spectral' in the test command instead of either of these approaches.

2024-02-23 13:41 UTC, tnederveld requested changes
See previous comment about using 'npx'

2024-02-23 22:01 UTC, DawMatt commented
> I'd suggest using 'npx spectral' in the test command instead of either of these approaches.

Updated as suggested via https://github.com/jmlue42/spectral-jsonapi-ruleset/pull/77/commits/dda130d315d2dfd942090fd4cc6aa98b212797f2 . I've retested on Windows and Mac and both work OK with this modification.

2024-03-10 00:22 UTC, tnederveld approved these changes

2024-03-10 01:42 UTC, DawMatt commented
Thanks @tnederveld . I note that this PR is still stating it needs 1 approving review, from a reviewer with write access. Does this mean I need another review beyond yours? Do you have write access to this repository?

@jmlue42 , could you please clarify?

2026-06-29 21:37 UTC, jmlue42 approved these changes

2026-06-29 21:54 UTC, merged